version: "3.9"


services:

  history-db:
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        SA_PASSWORD: "8zWt4!LmR6@kC3#eQb0"
        ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"
      networks:
        - calculator-network

  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    networks:
      - calculator-network
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - calculator-network

  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085
    networks:
      - calculator-network

  minusservice:
    build:
      context: .
      dockerfile: MinusService/Dockerfile
    image: thohol02/calculator-minusservice:$BUILD_NUMBER
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports:
      - 8980:80
    networks:
      - calculator-network

  multiplyservice:
    build:
      context: .
      dockerfile: MultiplyService/Dockerfile
    image: thohol02/calculator-multiplyservice:$BUILD_NUMBER
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports:
      - 8180:80
    networks:
      - calculator-network 

  plusservice:
    build:
      context: .
      dockerfile: PlusService/Dockerfile
    image: thohol02/calculator-plusservice:$BUILD_NUMBER
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports:
      - 8380:80
    networks:
      - calculator-network

  historyservice:
    build:
      context: .
      dockerfile: HistoryService/Dockerfile
    image: thohol02/calculator-historyservice:$BUILD_NUMBER
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports: 
      - 8280:80
    networks:
      - calculator-network
    depends_on:
      - history-db

  angular-app:
    build:
      context: ./CalculatorFrontend
      dockerfile: ./Dockerfile
    image: thohol02/calculator-angularapp:$BUILD_NUMBER
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - 4200:4200
    networks:
      - calculator-network

  nginx-proxy:
    build:
      context: ./CalculatorFrontend
      dockerfile: Dockerfile.nginx
    image: thohol02/calculator-nginx:$BUILD_NUMBER
    ports:
      - 8081:8081
      - 8084:8084
    networks:
      - calculator-network
    depends_on:
      - angular-app

volumes:
  rps_seq_data:
  featurehub-h2-data:
  
networks:
  calculator-network:
    external: true