version: "3.9"


services:

  history-db:
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        SA_PASSWORD: "8zWt4!LmR6@kC3#eQb0"
        ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"
      networks:
        - calculator-network

  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    networks:
      - calculator-network
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - calculator-network

  minusservice1:
    build:
      context: .
      dockerfile: MinusService/Dockerfile
    image: thohol02/calculator-minusservice1:$BUILD_NUMBER
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports:
      - 8180:80
    networks:
      - calculator-network

  minusservice2:
    build:
      context: .
      dockerfile: MinusService/Dockerfile
    image: thohol02/calculator-minusservice2:$BUILD_NUMBER
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports:
      - 8181:80
    networks:
      - calculator-network

  minusservice3:
    build:
      context: .
      dockerfile: MinusService/Dockerfile
    image: thohol02/calculator-minusservice3:$BUILD_NUMBER
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports:
      - 8182:80
    networks:
      - calculator-network
    
  plusservice1:
    build:
      context: .
      dockerfile: PlusService/Dockerfile
    image: thohol02/calculator-plusservice1:$BUILD_NUMBER
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports:
      - 8380:80
    networks:
      - calculator-network

  plusservice2:
    build:
      context: .
      dockerfile: PlusService/Dockerfile
    image: thohol02/calculator-plusservice2:$BUILD_NUMBER
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports:
      - 8381:80
    networks:
      - calculator-network

  plusservice3:
    build:
      context: .
      dockerfile: PlusService/Dockerfile
    image: thohol02/calculator-plusservice3:$BUILD_NUMBER
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports:
      - 8382:80
    networks:
      - calculator-network

  historyservice1:
    build:
      context: .
      dockerfile: HistoryService/Dockerfile
    image: thohol02/calculator-historyservice1:$BUILD_NUMBER
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports:
      - 8280:80
    networks:
      - calculator-network
    depends_on:
      - history-db

  historyservice2:
    build:
      context: .
      dockerfile: HistoryService/Dockerfile
    image: thohol02/calculator-historyservice2:$BUILD_NUMBER
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports:
      - 8281:80
    networks:
      - calculator-network
    depends_on:
      - history-db

  historyservice3:
    build:
      context: .
      dockerfile: HistoryService/Dockerfile
    image: thohol02/calculator-historyservice3:$BUILD_NUMBER
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=history-db;Database=histDbLocal;User Id=sa;Password=8zWt4!LmR6@kC3#eQb0;TrustServerCertificate=true;Connection Timeout=30;
    ports:
      - 8282:80
    networks:
      - calculator-network
    depends_on:
      - history-db

  angular-app1:
    build:
      context: ./CalculatorFrontend
      dockerfile: ./Dockerfile
    image: thohol02/calculator-angularapp1:$BUILD_NUMBER
    ports:
      - 4200:4200
    networks:
      - calculator-network

  angular-app2:
    build:
      context: ./CalculatorFrontend
      dockerfile: ./Dockerfile
    image: thohol02/calculator-angularapp2:$BUILD_NUMBER
    ports:
      - 4201:4200
    networks:
      - calculator-network

  angular-app3:
    build:
      context: ./CalculatorFrontend
      dockerfile: ./Dockerfile
    image: thohol02/calculator-angularapp3:$BUILD_NUMBER
    ports:
      - 4202:4200
    networks:
      - calculator-network

  nginx-proxy:
    build:
      context: ./CalculatorFrontend
      dockerfile: Dockerfile.nginx
    image: thohol02/calculator-nginx:$BUILD_NUMBER
    ports:
      - 8081:8081
      - 8084:8084
    networks:
      - calculator-network
    depends_on:
      - angular-app1
      - angular-app2
      - angular-app3

volumes:
  rps_seq_data:
  
networks:
  calculator-network:
    external: true